### ISSUE TITLE
Language defining in pluginOptions is ignoring

### ISSUE THREAD

**Issue by a-komarev** [kartik-v/yii2-widget-datepicker#10]
I'm using 1.2.0 widget with Russian language defined in application config:
```
'language' => 'ru-RU',
```
In this case all datepickers will use Russian language.

But if you want to use english language for specific widget - `pluginOptions` `language` property will be ignored:
```
$form->field($model, 'birthDate')->widget(
    DatePicker::classname(),
    [
        'convertFormat' => true,
        'pluginOptions' => [
            'language' => 'en',
            'endDate' => '31-12-1999',
            'format' => 'dd-MM-yyyy',
            'autoclose' => true,
            'startView' => 'decade',
        ]
    ]
);
```
`'language' => 'en-GB'` isn't working too. And even if no language setted in application config `pluginOptions` `language` will be ignored.

*// Assets were cleaned up on each test.*

**Comment by kartik-v** [comment]
While this fix is not related.. your issue is different:

You MUST not set `pluginOptions['language']` directly.. you must set the `language` property directly in the widget instead and it will get defaulted

```php
echo DatePicker::widget([
    'language' => 'en',
    'pluginOptions' => [
        'format'=>'dd-mm-yy'
    ]
])
```

**Comment by a-komarev** [comment]
Thanks. I've inspected widget's code and haven't found where `initLanguage()` is called :{

**Comment by kartik-v** [comment]
Please read my last comment again. The fix for initLanguage is not related to this widget or issue.

For your language related fix - DO NOT pass `pluginOptions['language']`, instead pass the `language` property in the widget settings directly.

```php
echo DatePicker::widget([
    'language' => 'en',
    'pluginOptions' => [
        'format'=>'dd-mm-yy'
    ]
])
```

**Comment by a-komarev** [comment]
Yes, I understood that and checked code already, it's working when language passing not as `pluginOptions['language']`. Asked about `function initLanguage()` just to clarify how it all works. I thought I missed something.
