### ISSUE TITLE
ID on input goes unrecognized for active  form 

### ISSUE THREAD

**Issue by samiksha-singla** [kartik-v/yii2-widget-datepicker#101]
Issue :

If I use this with custom id for input it does not show show model validations

       echo kartik\date\DatePicker::widget([
                 'model' => $model,
                 'form'=>$objActiveForm,
                 'attribute' => 'date_of_birth',
                 'options' => ['placeholder' => 'Enter birth date ...', 'id' => 'patient_dob'], **// with id clientside validations for model does not work**
                 'pluginOptions' => [
                     'format' => 'dd-mm-yyyy',
                     'endDate' => date('d-m-Y'),
                 ]
             ]);

While below code works 

  

     echo kartik\date\DatePicker::widget([
                 'model' => $model,
                 'form'=>$objActiveForm,
                 'attribute' => 'date_of_birth',
                 'options' => ['placeholder' => 'Enter birth date ...'],**//id is not used here**
                 'pluginOptions' => [
                     'format' => 'dd-mm-yyyy',
                     'endDate' => date('d-m-Y'),
                 ]
             ]);

But I want to use custom id .Any suggestions ?

**Comment by kartik-v** [comment]
Don't use it this way ...

Use it this way:

```php
use kartik\date\DatePicker;
echo $objActiveForm->widget(DatePicker::classname(), [
'options' => ['placeholder' => 'Enter birth date ...'],**//id is not used here**
     'pluginOptions' => [
         'format' => 'dd-mm-yyyy',
         'endDate' => date('d-m-Y'),
     ]
]);

**Comment by samiksha-singla** [comment]
Kartik , I have used it this way either but calendar input is not recognizing my custom id either way .
