### ISSUE TITLE
Not load language: problem with order that register js files

### ISSUE THREAD

**Issue by fgcarval** [kartik-v/yii2-widget-datepicker#103]
The DatePicker register js files in order:
<script src="/geo_pg/yii/web/assets/fe2c0ac9/js/bootstrap-datepicker.js"></script>
<script src="/geo_pg/yii/web/assets/fe2c0ac9/js/datepicker-kv.js"></script>
<script src="/geo_pg/yii/web/assets/fe2c0ac9/js/locales/bootstrap-datepicker.pt-BR.min.js"></script>
So an error occur:
Uncaught TypeError: Cannot read property 'dates' of undefined .....  bootstrap-datepicker.pt-BR.min.js:1

I change the order of loaded files and resolve my problem.
new order:
<script src="/geo_pg/yii/web/assets/fe2c0ac9/js/bootstrap-datepicker.js"></script>
<script src="/geo_pg/yii/web/assets/fe2c0ac9/js/locales/bootstrap-datepicker.pt-BR.min.js"></script>
<script src="/geo_pg/yii/web/assets/fe2c0ac9/js/datepicker-kv.js"></script>

Can you fix this?

**Comment by mplescano** [comment]
hi fgcarval:

can you show up the new order of loading, I hava the same problem.

Regards

**Comment by fgcarval** [comment]
Hi mplescano,

I modified the method "registerAssets" in DatePicker.php.

//            DatePickerAsset::register($view)->js[] = $this->_langFile;
            $firstJs = array_shift(DatePickerAsset::register($view)->js);
            array_unshift(DatePickerAsset::register($view)->js, $this->_langFile);
            array_unshift(DatePickerAsset::register($view)->js, $firstJs);

This resolve my problem.
I hope that helps you

**Comment by mplescano** [comment]
Thanks fgcarval, 
I was reviewing and I found the same issue in #96 
Regards

**Comment by markmarco16** [comment]
Hello @kartik-v, i have he same problem

bootstrap-datepicker.es.min.js:1 Uncaught TypeError: Cannot read property 'dates' of undefined

and the solution used by @fgcarval is great, maybe considers send PR.

Thanks!

**Comment by fsateler** [comment]
This was addressed on https://github.com/kartik-v/yii2-widget-datepicker/commit/3f7b38886e334a2c8c4262f155d98812461efd36 , but the change was reverted (probably accidentally) on https://github.com/kartik-v/yii2-widget-datepicker/commit/3888bae2d4f8dd0e9f0d9ce4ef1aa046aa836309 .

@kartik-v , could you please re-apply the fix?

**Comment by robmies1968** [comment]
Thanks fgcarval. Solved my problem, although I just copied your code and haven't got a clue how it works and why...  ;-)

**Comment by kartik-v** [comment]
Ensure you have latest release of the extension (which is currently v1.4.1). No other change to code is needed. There was a related issue which was resolved in #96.

Check an example of using language locales in the demos. For example [check the second example using French language here](http://demos.krajee.com/widget-details/datepicker#advanced-usage).
