### ISSUE TITLE
Date ru-RU or ru not correct when update

### ISSUE THREAD

**Issue by wilsonfalai** [kartik-v/yii2-widget-datepicker#11]
I use mysql language ru-RU and DateControl too
When I want to edit a record, the date field shows the correct date, but if I click on the calendar date field appears with today's date, forcing then use today's date by modifying the correct date.

To test I used the datepicker standard yii and not had this problem. The date on the calendar appeared correct.

**Comment by wilsonfalai** [comment]
I'm using DateControl too

**Comment by kartik-v** [comment]
For DateControl, your `saveFormat` and `displayFormat` must be correctly set - else it will NOTbe read correctly by widget. Check docs on how you must set this - note that these formats are ICU by default, and you need to prepend `php:` string if you are using a PHP date format.

**Comment by wilsonfalai** [comment]
I can not configure Display Format Defaulting Rules and nor Save Format Defaulting Rules, because the user of my system can change the language. According to the documentation, if I do not set these config that you said the format as set in Yii::$app->formatter will be used

If I use Pt or En language, I have no problem. The problem is that when ru-RU use the component sets the current date(today) and not the date of mysql when I click on the date field.

Sorry my english!

**Comment by kartik-v** [comment]
You may want to debug and check what format is being used for `saveFormat` and `displayFormat` when you use `ru-RU` - there maybe some error in converting to that format.

**Comment by wilsonfalai** [comment]
My configs

In config/main:
'language' => 'ru-RU'
and
'datecontrol' =>  ['class' => '\kartik\datecontrol\Module',]


In my View:
$form->field($model, 'data_nascimento')->widget(DateControl::classname(), [
                    'type'=>DateControl::FORMAT_DATE,
                    'ajaxConversion'=>false,
                    'options' => [
                        'pluginOptions' => [
                            'autoclose' => true
                        ]
                    ]
                ]);

after saving correctly:
The date field in mysql is:
2014-10-22
Y-m-d

**Comment by wilsonfalai** [comment]
![a](https://cloud.githubusercontent.com/assets/983312/5688075/534ffba8-983a-11e4-97db-41049ca2a476.png)

**Comment by wilsonfalai** [comment]
In english i have problem too
:(
![2](https://cloud.githubusercontent.com/assets/983312/5688138/13c2b998-983b-11e4-86d5-7173053b8784.png)

**Comment by kartik-v** [comment]
As I said, you may need to debug and see what is the **saveFormat** and **displayFormat** being generated from your Formatter settings for your environment for each language. Your date values must exactly follow the above format for save and display, else you will have conversions error

**Comment by kartik-v** [comment]
You need to set a constant **saveFormat** in your datecontrol module settings... and let **displayFormat** be picked from Yii formatter. I think that's the reason for your issue.

**Comment by wilsonfalai** [comment]
I did what you suggested and my problem continues. Set up only the SaveSettings. Is saving the value correctly.
Sorry! 

The returned value is using the medium format. How do I configure the component for the short format
In beforeAction i tryed:
Yii::$app->formatter->timeFormat = 'short';

I believe in Portuguese works because the format is numeric only. If I define for short, all languages ​​were with numerical value

**Comment by wilsonfalai** [comment]
Solved.
'displaySettings' => [
            Module::FORMAT_DATE => 'short',
        ],
i've set to 'short'

**Comment by kartik-v** [comment]
That's what I have been saying - try to set the **displayFormat** or **saveFormat** within the DateControl module - instead of relying on format derived from Yii Formatter (because that will not be consistent across languages). Hope you understood?

**Comment by wilsonfalai** [comment]
Sure.
Thak you!
