### ISSUE TITLE
Default value don't work in kartik datapicker dymanic form

### ISSUE THREAD

**Issue by salman67** [kartik-v/yii2-widget-datepicker#112]
Hi @kartik-v 
The default value in the kartik datepicker is not working in dynamic form after it is reinitialize(After the new form is added),
This is for Date-of-birth, the date of birth i want to start form 23-02-1982..

  <?= $form->field($dir, "[{$index}]owner_dob")->widget(DatePicker::classname(), [                                  "options" => ["placeholder" => "Date of Birth",
                        "value" => "23-02-1982",],
                        "id" => "dating",
                        "type" => DatePicker::TYPE_COMPONENT_APPEND,
                        "pluginOptions" => [
                          "format" => "dd-mm-yyyy",
                        "endDate" => date("d-m-Y"),
                        "autoclose"=>true,
                        ]])->label(false);?>  

Im using wbraganca\dynamicform\DynamicFormWidget, for dynamic form. all fields are coming properly except this datepicker.
After i reinitialize i get blank field, and the starting date is today's date. 

This is the js code im using for reinitialize..
$this->registerJs(<<<JS
    $(".dynamicform_wrapper").on('afterInsert', function(e, item) {
        var datePickers = $(this).find('[data-krajee-kvdatepicker]');
        datePickers.each(function(index, el) {
            $(this).parent().removeData().kvDatepicker('add');
            $(this).parent().kvDatepicker(eval($(this).attr('data-krajee-kvdatepicker')));
        });
    });
JS
, \yii\web\View::POS_END);

Reinitialize is happening but its coming blank fields and showing current date.

**Comment by Flashwade1990** [comment]
Try to add this line to the end of your datePickers.each loop: $('#your_model_name-' + index + '-owner_dob').val('23-02-1982');

**Comment by salman67** [comment]
@Flashwade1990 : Sorry for late reply, but its not working.. giving syntax error..`$('#dir' + index + '-owner_dob').val('23-02-1982');`

**Comment by salman67** [comment]
It says syntax error, unexpected '(', expecting variable (T_VARIABLE) or '$',  Is it correct which im doing, place of line?
` <?= $form->field($dir, "[{$index}]owner_dob")->widget(DatePicker::classname(), [                 
                          "options" => ["placeholder" => "Date of Birth",
                          "value" => "23-02-1982",
                          ],
                          "id" => "dating",
                          "type" => DatePicker::TYPE_COMPONENT_APPEND,
                          "pluginOptions" => [
                            "format" => "dd-mm-yyyy",
                          //'startDate' => date("1998-02-07 H:i:s"),
                          "endDate" => date("d-m-Y"),
                          "autoclose"=>true,
                          ]])->label(false);?>                  
                           <?php $('#dir-' + index + '-owner_dob').val('23-02-1982');?>`

**Comment by Flashwade1990** [comment]
You should add this line into your js script, not in php.

**Comment by salman67** [comment]
yeah now i added it in like this in the end of page,

 <script type="text/javascript">
                       $('#dir-' + index + '-owner_dob').val('23-02-1982');
                      </script>

**Comment by Flashwade1990** [comment]
You should add it here:
$this->registerJs(<<<JS
$(".dynamicform_wrapper").on('afterInsert', function(e, item) {
var datePickers = $(this).find('[data-krajee-kvdatepicker]');
datePickers.each(function(index, el) {
$(this).parent().removeData().kvDatepicker('add');
$(this).parent().kvDatepicker(eval($(this).attr('data-krajee-kvdatepicker')));
$('#dir-' + index + '-owner_dob').val('23-02-1982');
});
});
JS
, \yii\web\View::POS_END);

**Comment by Flashwade1990** [comment]
And no js errors in console?

**Comment by salman67** [comment]
no there are no errors.

**Comment by Flashwade1990** [comment]
Sorry.  Then I don't know how to help you.

**Comment by salman67** [comment]
Hmmm Thank you for your help.
