### ISSUE TITLE
Moment.js requirement

### ISSUE THREAD

**Issue by jeffwalsh** [kartik-v/yii2-widget-datepicker#119]
Hey there. The datepicker no longer works with new version of Moment.JS - it needs to be 2.12.0 or earlier. I'm unsure of where to update this requirement within the project. I'm able to get this to work by creating a bower.json in my project root, and requiring the correct, earlier version of Moment there.

**Comment by kartik-v** [comment]
Not sure this is correct. This widget does not require moment.js. 

The extension that uses moment.js is [yii2-date-range](https://github.com/kartik-v/yii2-date-range) and that has its own moment.js and does not link to the repo of moment.

**Comment by jeffwalsh** [comment]
Whoops - truth, it is date-range. My yii2-date-range still pulls from the different Moment.js in my vendor folder, and not to your moment.js which is the correct version.
I'll take a look, thanks.
