### ISSUE TITLE
default z-index is awful!

### ISSUE THREAD

**Issue by TrueZurg** [kartik-v/yii2-widget-datepicker#124]
Hello!
You have code in your css:
`.datepicker {
    z-index: 1151 !important;
}`

I think that is a bad idea to make z-index important with so low value.
Please, make it not important, or increase value to 2147483647 or some other very big number.

**Comment by lobjects** [comment]
Hi,
Excellent Work!! Thanks.
Calendar is shown behind the bootstrap navbar. screen shot attached. Tried changing the z-index on datepicker but didn't work
![image](https://user-images.githubusercontent.com/9503186/44955035-49d32000-aeca-11e8-8ed1-5eee03b02efa.png)

Thanks
