### ISSUE TITLE
DatePicker widget refresh muti-times and not stop

### ISSUE THREAD

**Issue by hbxjw119** [kartik-v/yii2-widget-datepicker#129]
Is this is a bug? When I use \kartik\date\DatePicker in \kartik\grid\GridView as a column filter, if I give option 'type' => DatePicker::TYPE_INPUT, my index page refresh muti-times and not stop. Here 's my code:
$gridColumn = [
[
'attribute' => 'licence_expire_date',
'value' => function ($model) {
return Carbon::createFromTimestamp($model->licence_expire_date, Yii::$app->timeZone)->toDateString();
},
'filterType' => GridView::FILTER_DATE,
'filterWidgetOptions' => [
'type' => DatePicker::TYPE_INPUT,
'removeButton' => false,
'pluginOptions' => [
'autoclose'=>true,
'format'=>'yyyy-mm-dd'
]
],

],
];

echo GridView::widget([
'id' => 'staff-grid',
'dataProvider' => $dataProvider,
'filterModel' => $searchModel,
'columns' => $gridColumn,

**Comment by kartik-v** [comment]
It probably is a source plugin behaviour which is triggering a change for INPUT type on init... that causes the yii grid filter to fire again causing infinite loop.

You may want to report this to datepicker plugin author. Alternatively do not use TYPE_INPUT and use one of the other types like TYPE_PREPEND. Will need to check for enhancement later.
