### ISSUE TITLE
php 7.1 Setting unknown property: kartik\date\DatePicker::_container

### ISSUE THREAD

**Issue by phpyii** [kartik-v/yii2-widget-datepicker#139]
```
                   echo DatePicker::widget([
                        'model' => $model,
                        'attribute' => 'date',
                        'type' => DatePicker::TYPE_INPUT,
                        'form' => $form,
                        'pluginOptions' => [
                            'format' => 'yyyy-mm',
                            'autoclose' => true,
                            'startView' => 'months',
                            'maxViewMode' => 'years',
                            'minViewMode' => 'months'
                        ]
                    ]);
```
php 7.0.19 is ok
php 7.1.5  is error
![qq 20170522133245](https://cloud.githubusercontent.com/assets/3365344/26294007/5efc1a56-3ef3-11e7-9c65-2548dca0e8b6.png)

**Comment by joncojonathan** [comment]
I have the same problem on PHP v7.1.2.  My code was working fine, now I get the same error as @phpyii following an upgrade.

@kartik-v any suggestions?

**Comment by phpyii** [comment]
@joncojonathan 
I changed it this way
```
$form->field($model, 'created_at')->widget(DatePicker::className(),[
                        'type' => DatePicker::TYPE_INPUT,
                        'removeButton' => ['icon' => 'trash'],
                        'pickerButton' => false,
                        'pluginOptions' => [
                            'format' => 'yyyy-mm-dd',
                            'autoclose' => true,
                            'todayHighlight' => true,
                        ]
                ])
```

**Comment by kartik-v** [comment]
Yes use as @phpyii suggested.

**Comment by hodari00** [comment]
what if i can't use $model?
<?= DatePicker::widget([
                            'type' => DatePicker::TYPE_INPUT,
                            'name' => $frag.'[start_dt]',
                            'value' => $model->start_dt,
                            'removeButton' => ['icon' => 'trash'],
                        'pickerButton' => false,
                          'options' => DynamicRelations::uniqueOptions('start_dt',$uniq,Yii::t("app", "Start date"),'form-control required'),
                           // 'options' => [DynamicRelations::uniqueOptions('start_dt',$uniq), 'placeholder' => Yii::t("app", "Start date")],
                            'pluginOptions' => [
                                'format' => 'yyyy-mm-dd',
                                'todayHighlight' => true,
                                'autoclose' => true,
                            ]
                    ]);?>

**Comment by hodari00** [comment]
what if i can't use $model, and am using name and value?

**Comment by kartik-v** [comment]
Read docs. Its similar to as using any other Input Widget... [check the demo example here](http://demos.krajee.com/widget-details/datepicker#markup-comp-app)

**Comment by hodari00** [comment]
With PHP 7.1, using that way gives me the error OP is facing

**Comment by joncojonathan** [comment]
@hodari00 can you provide some example code?

**Comment by kartik-v** [comment]
@hodari00 I cannot reproduce any error on PHP 7.1.x ... can you share your code and configuration.

**Comment by hodari00** [comment]
i updated the PHP version and its fine now. thanks
