### ISSUE TITLE
Language option problem

### ISSUE THREAD

**Issue by massimilianomancini** [kartik-v/yii2-widget-datepicker#14]
With last version 35a6925 it seems that language option doesn't go.
This is my example
`
<?= $form->field($son, 'lBirthDate', ['enableAjaxValidation' => true])->widget(DatePicker::classname(), ['pluginOptions' => ['autoclose'=>true, 'language' =>'it']]) ?>
`
![calendar](https://cloud.githubusercontent.com/assets/8819943/5839216/fe82a402-a18c-11e4-940d-458393892a56.png)

**Comment by kartik-v** [comment]
You have wrongly put `language` inside `pluginOptions`. It should be passed at the widget level.
