### ISSUE TITLE
Class 'kartik\widgets\DatePicker' not found

### ISSUE THREAD

**Issue by mjb16** [kartik-v/yii2-widget-datepicker#140]
I tried to install DatePicker. I Already sucsess use this DatePicker. But when im update the composer or I add new widget on my vendor, I get this error `Class 'kartik\widgets\DatePicker' not found` . I tried to remove vendor and copy back. but i still get this error. please help me

**Comment by xenogenesi** [comment]
I had the same error, solved using `use kartik\date\DatePicker;` (as seen  in`vendor/composer/autoload_psr4.php`)
