### ISSUE TITLE
How to add error messages for DateValidation?

### ISSUE THREAD

**Issue by JaroslavTarasov** [kartik-v/yii2-widget-datepicker#142]
In my model I use DateValidation 

`['date_birthday', 'date', 'format' => 'd.m.yy', 'min' => '01.01.1900', 'max' => date('d.m.yy'), 'tooSmall'=>'The date is from past. Try another','tooBig' => 'The date is from future. Try another', 'message' => 'Try to input the date'],`

In view I call the widget

```
 <?php echo $form->field($modelForm, 'date_birthday')->widget(\kartik\date\DatePicker::classname(), [
                        'type' => \kartik\date\DatePicker::TYPE_COMPONENT_APPEND,
                        'pickerButton' => false,
                        'options' => [
                            'placeholder' => '',
                        ],
                        'pluginOptions' => [
                            'format' => 'dd.mm.yyyy',
                            'autoclose' => true,
                            'showMeridian' => true,
                            'startView' => 2,
                            'minView' => 2,
                        ]
                    ]) ?>
```

It checks for min and max dates, but show no error message. How to fix it?

**Comment by kamran377** [comment]
add this css in your page, it will display errors on datepicker
`<style>
	.invalid-feedback{display:block !important}
</style>`
