### ISSUE TITLE
'format' => 'php:Y-m-d H:i:s'

### ISSUE THREAD

**Issue by bscheshirwork** [kartik-v/yii2-widget-datepicker#143]
How about add to the 'format' property `datetimeFormat` format like `i18n\Formatter` of yii2?
[$datetimeFormat](http://www.yiiframework.com/doc-2.0/yii-i18n-formatter.html#$dateFormat-detail)

Or directly use it?

**Comment by kartik-v** [comment]
This is the yii2-widget-datepicker extension which supports only date formats. 

You need to use the [yii2-widget-datetimepicker](https://github.com/kartik-v/yii2-widget-datetimepicker) extension for date time formats.

**Comment by bscheshirwork** [comment]
Anyway, `php:` format is not implemented. 

And `yii2-widget-datepicker` can be used with zero-filled time in `dateTime` field
```php
                    'value' => $searchModel->dateTimeField,
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd 00:00:00',
                    ]
```
