### ISSUE TITLE
How to update date?

### ISSUE THREAD

**Issue by robogame** [kartik-v/yii2-widget-datepicker#146]
If I use DatePicker::TYPE_INPUT, when I update the date value, I can use 
` <?= $form->field($model, 'dateline')->widget(DatePicker::classname(), 
                  [ 
                     'type' => DatePicker::TYPE_INPUT,
                     'options' => ['placeholder' => '选择时间'], 
                     'value' => '23-Feb-1982',
                     'pluginOptions' => [ 
                         'autoclose' => true, 
                         'todayHighlight' => true, 
                         'format' => 'yyyy-mm-dd', 
                     ] 
                  ])->textInput(['value' => date('Y-m-d', $model->dateline)]); 
    ?>
`
But when I use DatePicker::TYPE_RANGE, How can I load the input value from model?

**Comment by robogame** [comment]
` <?= $form->field($model, 'dateline')->widget(DatePicker::classname(), 
                  [ 
                    'attribute' => 'dateline',
                    'attribute2' => 'stopline',
                    'options' => ['placeholder' => '开始日期'],
                    'options2' => ['placeholder' => '截至日期'],
                    'type' => DatePicker::TYPE_RANGE,
                     'pluginOptions' => [ 
                         'autoclose' => true, 
                         'todayHighlight' => true, 
                         'format' => 'yyyy-mm-dd', 
                     ] 
                  ])->label('起始日期')->textInput(['value' => date('Y-m-d', $model->dateline)]); ; 
            ?>`

**Comment by isamuhiro** [comment]
same issue here
have you found a solution, @robogame ?
