### ISSUE TITLE
jQuery 3 - un-rendered date picker

### ISSUE THREAD

**Issue by iBotPeaches** [kartik-v/yii2-widget-datepicker#147]
![screen shot 2017-09-01 at 4 41 35 pm](https://user-images.githubusercontent.com/611784/29987090-6fa65a42-8f34-11e7-95fc-dc73d562b1a6.png)

PR inbound. Requires update of upstream package to 1.7.1

**Comment by kartik-v** [comment]
Resolved via [update to release v1.4.3](https://github.com/kartik-v/yii2-widget-datepicker/commit/b793655b63e77e5598ed232cf887cc640c30420f).
