### ISSUE TITLE
Date selection box not appearing

### ISSUE THREAD

**Issue by shaqman** [kartik-v/yii2-widget-datepicker#153]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-datepicker.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/datepicker).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (datepicker) issue. (Those should be directed to the [plugin issues repo](https://github.com/datepicker/datepicker/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Normal usage, using code below. (works on 1.4.1 with jQuery 2.2.4)
```
 $form->field($model, 'date')->widget(DatePicker::classname(), [
        'options' => ['placeholder' => Yii::$app->params['htmlControlDateFormat'], 'readonly' => 'readonly'],
        'pluginOptions' => [
            'autoclose' => true,
            'startView' => 'year',
            'minViewMode' => 'weeks',
            'format' => Yii::$app->params['htmlControlDateFormat'],
            'startDate' => '+71d'
        ]
    ])
```

## Expected behavior and actual behavior

When I follow those steps, I see an empty popover (no date selection).
With this error in console:

```
Uncaught TypeError: Cannot read property 'clsName' of undefined
    at Datepicker.setViewMode (bootstrap-datepicker.js:1494)
    at new Datepicker (bootstrap-datepicker.js:147)
    at HTMLDivElement.<anonymous> (bootstrap-datepicker.js:1644)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at jQuery.fn.init.datepickerPlugin [as kvDatepicker] (bootstrap-datepicker.js:1626)
    at HTMLDocument.<anonymous> (create:1072)
    at mightThrow (jquery.js:3583)
    at process (jquery.js:3651)
```

I was expecting, date picker is shown.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.1
- yii2-widget-datepicker version: 1.4.4

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/datepicker)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-widget-datepicker without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by rklvnoe** [comment]
Found a solution added in bootstrap-datepicker.js
Line 480
this.picker.find('>div').hide().filter('.datepicker-'+DPGlobal.viewModes[this.viewMode].clsName).css('display', 'block');;

After that the datepicker works.
Maybe you have got a better idea.

Nice Greetings
Ian
