### ISSUE TITLE
 The plugin is not working on the new version of Yii

### ISSUE THREAD

**Issue by ASYOU99** [kartik-v/yii2-widget-datepicker#154]
After updating Yii to version 2.0.13 the plug-in stopped working, most likely because of the transition to the version of jquery 3

**Comment by ASYOU99** [comment]
You can upgrade your plugins for compatibility with the 3 version of jquery?

**Comment by valieand** [comment]
+1

**Comment by kurniawantaari** [comment]
I have same problem here.

**Comment by divad942** [comment]
+1

**Comment by xavsio4** [comment]
+1

**Comment by valieand** [comment]
+1

**Comment by Commifreak** [comment]
@xavsio4 Whats your fix? I have the same problem. As soon as editable css is also loaded, the datepicker does not appear.

**Comment by kartik-v** [comment]
Fixed via latest release v1.4.4
