### ISSUE TITLE
How to use the object version of the 'format' attribute (pluginOptions)

### ISSUE THREAD

**Issue by joanlopez** [kartik-v/yii2-widget-datepicker#158]
Dear @kartik-v,

I'm trying to use the following format attribute:
http://bootstrap-datepicker.readthedocs.io/en/latest/options.html#format

However, I'm not able to pass the proper functions.

My current code looks like:
```
'pluginOptions' => [
                'format' => "{
                  'toDisplay' => function(date){console.log('display'); console.log(date); return new Date(date);},
                  'toValue' => function(date){console.log('value'); console.log(date); return new Date(date);}}",
                'todayHighlight' => true,
                'daysOfWeekDisabled' => '06',
                'startDate' => date('y-d-m')
              ]
```

I'm also currently using the 'pluginEvents' and it's works well (congratulations for your job!) as the other attributes of 'pluginOptions'. Furthermore, the string version of the 'format' attribute is also working properly.

So, which is the proper way to pass an object to the 'format' attribute?
Is it really possible with your widget?

Thanks a lot! ;)

**Comment by kartik-v** [comment]
You need to escape such properties with `yii\web\JsExpression` else Yii will wrongly pass everything as a string... (BTW this has nothing to do with this extension - and more a reading you may want to do on yii JSON encoding)

```php
'format' => new yii\web\JsExpression("{
    'toDisplay' => function(date){console.log('display'); console.log(date); return new Date(date);},
    'toValue' => function(date){console.log('value'); console.log(date); return new Date(date);}
}"
```

**Comment by joanlopez** [comment]
Thanks a lot @kartik-v!!!

Sorry for my ignorance, I'm just starting with Yii and I don't know this kind of "tricks" yet.
