### ISSUE TITLE
Datepicker is not working with modal

### ISSUE THREAD

**Issue by tgrafen1** [kartik-v/yii2-widget-datepicker#159]
## Prerequisites
Hello Kartik,
i have a similar problem like the other posts i found, but none of this solutions is working or there is no real solution. im using yii 2.0 with the latest yii2-widget-datepicker. When im open my modal the dialog with the datepicker is not showing, but when im using the dapicker on a normal site, it is showing.

Browsers

- [X ] Google Chrome
- [x] Mozilla Firefox
- [X ] Internet Explorer
- [X] Safari

Libraries
- yii2-widget-datepicker version:

**Comment by lgcelarie** [comment]
I'm having the same issue, when used in a Modal loaded via Ajax. If i use it with a modal thats not rendered via ajax there's no issue; only with the view rendered by ajax, even though i'm using the renderAjax method

**Comment by papppeter** [comment]
Hi,

i think the following css part makes the problem:

datepicker-kv.css
.datepicker {
    z-index: 1151 !important;
}

it just overrides the syle z-index.

could we maybe remove this line? that would fix modal.

**Comment by jcrawford** [comment]
I am also having this issue I believe.  The fix of removing !important from the z-index did not seem to fix the issue.  However my modal for the date picker only wants to look like this without any errors to give direction.

![screen shot 2018-06-07 at 10 15 59 am](https://user-images.githubusercontent.com/875341/41162765-cd37ad76-6b04-11e8-9717-e24853e25748.png)

**Comment by samsadbeagum** [comment]
Call the function below in the Ajax callback used to render a dynamic modal.

function initKartikDatePicker(){
            jQuery.fn.kvDatepicker.dates={}; 
            if (jQuery('#w0').data('kvDatepicker')) { jQuery('#w0').kvDatepicker('destroy'); } 
            jQuery('#w0-kvdate').kvDatepicker(kvDatepicker_cba0ddb4); 
            initDPRemove('w0'); 
            initDPAddon('w0'); 
        }

**Comment by samsadbeagum** [comment]
Fix for showing a date-picker dynamically in a bootstrap modal in yii2 application:
1. Added a date-picker near the modal's close button and set its visibility to hidden.
   <?php echo DatePicker::widget([ 'name' => 'hiddenDatePicker',
             'type' => DatePicker::TYPE_INPUT,
             'options' => ['style'=>'visibility:hidden'],
             'pluginOptions' => [
                        'autoclose'=>true,
                        'format' => 'dd/mm/yyyy'
                    ] 
    ]); ?>
2. Called the function below in the Ajax callback used to render a dynamic modal.
function initKartikDatePicker(){
   jQuery.fn.kvDatepicker.dates={};
   if (jQuery('#w0').data('kvDatepicker')) { jQuery('#w0').kvDatepicker('destroy'); }
   jQuery('#w0-kvdate').kvDatepicker(kvDatepicker_cba0ddb4);
   initDPRemove('w0');
   initDPAddon('w0');
}

**Comment by tomislav-agilosit** [comment]
I am using jui datepicker with the same issue. The problem is probably in html attribute id that is being generated along 
with js code that runs the picker. Solution is to use different id somehow, or if you are using ActiveForm you can use DynamicModel to create different id, and then catch it in controller with Yii::$app->request->post('DynamicModel')['dob']:
if($model->isNewRecord) {
                    $dateModel = $model;
                } else { 
                    // Workaround for update
                    $dateModel = new DynamicModel([
                        'dob' => $model->dob
                    ]);
                }
echo $form->field($dateModel, 'dob')->widget(\yii\jui\DatePicker::class, [
                    'language' => 'hr',
                    'dateFormat' => 'dd.MM.yyyy.'
                ])

**Comment by lourdas** [comment]
I've been experiencing this issue and I have yet to find a valid solution. I'm using a Dialog modal that contains a DatePicker widget which is not displayed. I even tried the solution at the previous comment with the DynamicModel but still no luck.
