### ISSUE TITLE
Wrong Serbian Latin language code (sr-latin vs. sr-latn)

### ISSUE THREAD

**Issue by IgorCode** [kartik-v/yii2-widget-datepicker#167]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-datepicker.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/datepicker).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (datepicker) issue. (Those should be directed to the [plugin issues repo](https://github.com/datepicker/datepicker/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Expected behavior and actual behavior

Serbian Latin language code is wrong, it should be "sr-latn" not "sr-latin", I see that for Uzbekistan Latin language code is "uz-latn" so not sure why Serbian has different one, also [Yii uses "sr-Latn"](https://github.com/yiisoft/yii2/tree/master/framework/messages/sr-Latn) which obviously does not work in DatePicker widget.

**Comment by kartik-v** [comment]
These locales files are from the source plugin repo (you may want to check with the author)
