### ISSUE TITLE
ShowOtherMonths

### ISSUE THREAD

**Issue by 112Legion112** [kartik-v/yii2-widget-datepicker#169]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-datepicker.
- [x] This is not a usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/datepicker).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (datepicker) issue. (Those should be directed to the [plugin issues repo](https://github.com/datepicker/datepicker/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.  Create widget ActiveForm 
2.  In one field for date attribute use DatePicker.
3.  Set **showOtherMonths** to _false_
![image](https://user-images.githubusercontent.com/20613430/42416712-1973bdd6-8290-11e8-8bac-0a1bff662a7a.png)

## Expected behavior and actual behavior

When I follow those steps, I see...
The others months are shown 
![image](https://user-images.githubusercontent.com/20613430/42416734-86f889f4-8290-11e8-905d-c982d49f44fa.png)

I was expecting...
Didn't see those months 

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- yii2-widget-datepicker version:

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/datepicker)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-datepicker without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
There is no plugin option available as far as I know called `showOtherMonths`. Check documentation of what [options are supported by the bootstrap-datepicker plugin](https://bootstrap-datepicker.readthedocs.io/en/stable/options.html).

**Comment by 112Legion112** [comment]
@kartik-v Well
Is there a way to get those dates?
![image](https://user-images.githubusercontent.com/20613430/42420002-96f7c0c0-82d8-11e8-8793-965b85f4a028.png)
