### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by Baha2Odeh** [kartik-v/yii2-widget-datepicker#175]
- kartik-v/yii2-widget-datepicker dev-master requires kartik-v/yii2-krajee-base ~1.9 -> no matching package found.                         
      - kartik-v/yii2-widget-datepicker 1.4.x-dev requires kartik-v/yii2-krajee-base ~1.9 -> no matching package found.                          
      - Installation request for kartik-v/yii2-widget-datepicker @dev -> satisfiable by kartik-v/yii2-widget-datepicker[1.4.x-dev, dev-master].

**Comment by kartik-v** [comment]
Update to latest via composer.
