### ISSUE TITLE
Date selection not shown

### ISSUE THREAD

**Issue by rklvnoe** [kartik-v/yii2-widget-datepicker#176]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of yii2-widget-datepicker.
- [x ] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/datepicker).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] This is not a source plugin (datepicker) issue. (Those should be directed to the [plugin issues repo](https://github.com/datepicker/datepicker/search?q=&type=Issues)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. `<div class="col-lg-9">
                    <?= $form->field($person, 'P_GEB_DATUM')->widget(DatePicker::class, [
                        'options' => ['placeholder' => 'Enter birth date ...'],
                        'pluginOptions' => [
                            'autoclose' => true
                        ]
                    ]) ?>
                </div>`

## Expected behavior and actual behavior

When I follow those steps, I see 
![image](https://user-images.githubusercontent.com/26544833/47289352-9b5e7800-d5fa-11e8-8858-b0ebd8bb8012.png)

I was expecting to see the datepicker

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.1
- yii2-widget-datepicker version: 1.4.7

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/datepicker)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-datepicker without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
duplicate to #177
