### ISSUE TITLE
setStartdate ,setEnddate is not working

### ISSUE THREAD

**Issue by ajkosh** [kartik-v/yii2-widget-datepicker#18]

**Comment by ajkosh** [comment]
this is not working
 $('#report-start_date').datetimepicker('setStartDate', '2014-01-01');

**Comment by kartik-v** [comment]
You are using the wrong plugin above `datetimepicker`... you need to use `datepicker`... secondly please check the source plugin docs for more details (or post to the plugin repo if you have plugin specific queries)?

**Comment by ajkosh** [comment]
setStartDate with datepicker  is not working also.there is no option in your widget to setStartDate and setEndDate,even no minDate or maxDate,but it is avaialble in bootstrap datepicker

**Comment by kartik-v** [comment]
you can set plugin options through `pluginOptions` so whatever the source plugin supports can be set through pluginOptions.. as I mentioned please read docs... if you need to use plugin methods  then you need to write your own javascript.

**Comment by ressac** [comment]
$form->field($model, 'MODEL')->widget(DateControl::classname(), [
        'type' => DateControl::FORMAT_DATE,
        'ajaxConversion' => false,
        'options' => [
            'pluginOptions' => [
                "startDate" => (string) date('d/m/Y'),
                "endDate" => (string) date('d/m/Y',time() + (DAYS * 24 * 60 * 60)),
                'autoclose' => true
            ],
        ]
    ]);

**Comment by kartik-v** [comment]
Depending on what is your data and date formats you need to trace and debug where you have the configuration issue.

For starters - test the above with a simple DatePicker with simple settings and  using it without DateControl.

Once that works - you may check within DateControl. Remember the DateControl widget will need strict date formats to be followed for display and save - for both your database data and displayed data.

**Comment by ressac** [comment]
i'm using 'saveFormat' => 'php:U' but after submit form i have var = '0'
what may cause this ?

**Comment by Aplear** [comment]
Hi! But how I can change calendar limit in dynamic?

**Comment by rohitbelocumindia** [comment]
Exactly same issues, dependent on type.
$("#slot-selectdatesingle").kvDatepicker("setStartDate", new Date(2021, 12, 12));
                        $("#slot-selectdatesingle").kvDatepicker('refresh');

                        jQuery('#slot-selectdatesingle-disp-kvdate').kvDatepicker('setStartDate', response.date);
                        jQuery('#slot-selectdatesingle-disp-kvdate').kvDatepicker("refresh");

Not work after ajex call reset StartDate
