### ISSUE TITLE
How to fix isBs4()??

### ISSUE THREAD

**Issue by jobsrey** [kartik-v/yii2-widget-datepicker#180]
i got error in datepicker?

`echo $form->field($model, 'tgl_lhr')->widget(DatePicker::classname(), [
        'options' => ['placeholder' => 'Tanggal Lahir ...'],
        'pluginOptions' => [
            'autoclose'=>true
        ]
    ]);`

result error:

Calling unknown method: kartik\\date\\DatePicker::isBs4()","code":0,"type":"yii\\base\\UnknownMethodException","file":"/opt/lampp/htdocs/myproject/school/_protected/vendor/yiisoft/yii2/base/Component.php","line":300,"stack-trace":["#0 /opt/lampp/htdocs/myproject/school/_protected/vendor/kartik-v/yii2-widget-datepicker/src/DatePicker.php(238)

**Comment by kartik-v** [comment]
You need to update your packages via Composer. This error occurs if you have tried to just manually copy the extension files without updating the dependencies.

**Comment by jobsrey** [comment]
Thx kartik-v
