### ISSUE TITLE
Clear button not working with pjax

### ISSUE THREAD

**Issue by darodriguez1994** [kartik-v/yii2-widget-datepicker#181]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-widget-datepicker.
- [X] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/datepicker).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] This is not a source plugin (datepicker) issue. (Those should be directed to the [plugin issues repo](https://github.com/datepicker/datepicker/search?q=&type=Issues)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Install yii2-widget-datepicker
2. Put it in a filter of a yii2\grid-view
3. Put the grid view inside an pjax container
4. Set the property "pjaxContainerId" the same as the id of the pjax container.

## Expected behavior and actual behavior
The clear button works in every filter action.

So, the issue is that the clear button only works in the first load of the page, after a filter action, the button doesn't work anymore, the widget do work but not the clear button.

**Comment by brantsx** [comment]
Has this ever been investigated?

**Comment by porcelanosa** [comment]
The same issue, but not everywhere
