### ISSUE TITLE
Correct way for include this widget with bootstrap 4

### ISSUE THREAD

**Issue by ludimassa** [kartik-v/yii2-widget-datepicker#190]
Hi everyone,
in my project I have removed bootstrap3 and I have only bootstrap4

But I am unable to use it 
This is the exception genereted:

You must install 'yiisoft/yii2-bootstrap' extension for Bootstrap 3.x version support. Dependency to 'yii2-bootstrap' has not been included with 'yii2-krajee-base'. To resolve, you must add 'yiisoft/yii2-bootstrap' to the 'require' section of your application's composer.json file and then run 'composer update'.

NOTE: This dependency change has been done since v2.0 of 'yii2-krajee-base' because only one of 'yiisoft/yii2-bootstrap' OR 'yiisoft/bootstrap4' bootstrap extensions can be installed. The developer can thus choose and control which bootstrap extension library to install.

What is the correct way for use this module with BS 4

**Comment by ludimassa** [comment]
by Reading the code inside the package I have solved  my question.
In every view file where you want include the widget add the code:
`Yii::$app->params['bsVersion'] = '4.x';`

The code isn't unable to determine what is your bootstrap version

I suggest to improve the documentation

**Comment by kartik-v** [comment]
It seems you have not read the documentation correctly. 

Read the [Bootstrap Info Section](https://demos.krajee.com/widget-details/datepicker#bs-info) of the widget's documentation to understand what you must configure and where depending on your application need.

**Comment by raezon** [comment]
i have an issue with date-picker it does not want to take bootstrap 4
