### ISSUE TITLE
Problem with version 14b17ce

### ISSUE THREAD

**Issue by massimilianomancini** [kartik-v/yii2-widget-datepicker#20]
After update to version 14b17ce I've got some problems:
1. language is ignored both from yii2 config and as widget option
2. clicking on month or year, result is as attached screenshots

Thanks
![year](https://cloud.githubusercontent.com/assets/8819943/6188089/2fdba0cc-b38e-11e4-9d6b-3419d31a6f89.png)
![years](https://cloud.githubusercontent.com/assets/8819943/6188090/2fdd0160-b38e-11e4-9cb6-089931d6542a.png)

**Comment by kartik-v** [comment]
As a rule, after you update extensions:

- Clear your runtime assets folder
- Clear your browser client cache and restart
- Ensure you have the updated release (versions) of the packages and its dependencies (should happen automatically if you use composer update)

You may have a problem with the first two points.

Lastly language is a property set at widget level - you may check docs/demos.
