### ISSUE TITLE
yii\base\UnknownMethodException: Calling unknown method: kartik\date\DatePicker::isBs() in /var/app/current/vendor/yiisoft/yii2/base/Component.php:301

### ISSUE THREAD

**Issue by adamwinn** [kartik-v/yii2-widget-datepicker#200]
I upgraded to the latest Datepicker version (1.4.8) and now I get 
```
yii\base\UnknownMethodException: Calling unknown method: kartik\date\DatePicker::isBs() in /var/app/current/vendor/yiisoft/yii2/base/Component.php:301
```
Downgrading to `1.4.7` fixes the bug

**Comment by FreekGille** [comment]
@adamwinn I was running into the same issue. Updating `kartik-v/yii2-krajee-base` to >3.0 fixed the issue as I was still on 2.x. Hope this helps!

**Comment by kartik-v** [comment]
Yes you need to upgrade rather than downgrade to solve the problem. Update all packages with dependencies to latest release via composer (do not manually copy the files to install).
