### ISSUE TITLE
a BOM in a ru/kvdate.php file

### ISSUE THREAD

**Issue by germansokolov13** [kartik-v/yii2-widget-datepicker#23]
After the last commit a strange whitespace appeared before the widget. Somehow some non-printable characters appeared there. I was able to solve this problem simply by saving the aforementioned file in utf-8 but without a BOM. Saving it with BOM returns the problem back.

**Comment by kartik-v** [comment]
Thanks could you submit a PR with the change.

**Comment by kartik-v** [comment]
Thanks could you submit a PR with the change.

**Comment by kartik-v** [comment]
Fixed by #24.
