### ISSUE TITLE
Problem with translations

### ISSUE THREAD

**Issue by RomeroMsk** [kartik-v/yii2-widget-datepicker#25]
DatePicker widget is trying to get message file from `yii2-widgets/messages`, not from `yii2-widget-datepicker/messages`:
```
The message file for category 'kvdate' does not exist: /.../vendor/kartik-v/yii2-widgets/messages/ru-RU/kvdate.php Fallback file does not exist as well: /.../vendor/kartik-v/yii2-widgets/messages/ru/kvdate.php
/.../vendor/kartik-v/yii2-widget-datepicker/DatePicker.php (225)
/.../vendor/kartik-v/yii2-widget-datepicker/DatePicker.php (256)
/.../vendor/kartik-v/yii2-widget-datepicker/DatePicker.php (203)
```

**Comment by kartik-v** [comment]
You need to use `kartik\date\DatePicker` as your namespace for the widget and it should use **yii2-widget-datepicker/messages** folder.. If you use `kartik\widgets\DatePicker` as your namespace, then it will use the **yii2-widgets/messages** folder.

**Comment by kartik-v** [comment]
Anyway, I will improve this through an enhancement.

**Comment by RomeroMsk** [comment]
Yes, this solves the problem. Will check an enhancement too. Thanks.

**Comment by kartik-v** [comment]
Resolved with latest commit.

You can check with updated packages via composer in sometime (note your composer must update yii2-krajee-base and yii2-widgets / yii2-widget-datepicker).

**Comment by RomeroMsk** [comment]
Checked, all fine :+1:
