### ISSUE TITLE
datepicker design

### ISSUE THREAD

**Issue by YairHadari** [kartik-v/yii2-widget-datepicker#26]
Hi,

The following code reproduce the attached screen.
Is there a way I can disable the classes being loaded or the style being used (style="top: 129px; left: -822px; z-index: 10; display: block;") so the calendar will look better?
I"m using bootstrap-rtl.min.css

    <?php 
	$form = ActiveForm::begin(); 
		echo "<div class='col-md-2'>";
			echo '<label class="control-label">Date</label>';
			echo DatePicker::widget([
				'language' => 'en',
				'name' => 'storageItemsOrderDate',
	    			'type' => DatePicker::TYPE_COMPONENT_PREPEND,
		    		'pluginOptions' => [
					'autoclose'=>true,
					'format' => 'dd-mm-yyyy',
	    			]
			]);
		echo "</div>";
    ?>	
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
![yii2-katrik-datepicker](https://cloud.githubusercontent.com/assets/7589238/6599945/3785cb54-c815-11e4-9227-01e88388501f.jpg)

**Comment by kartik-v** [comment]
Set `pluginOptions['rtl'] = true` and try.

**Comment by mohamedyasser** [comment]
> Set `pluginOptions['rtl'] = true` and try.

not working
