### ISSUE TITLE
Update to latest version of bootstrap-datepicker

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-widget-datepicker#28]

**Comment by trinhkethanh** [comment]
I update new version then this error:

bootstrap-datepicker.vi.min.js:1 Uncaught TypeError: Cannot read property 'dates' of undefined

![untitled](https://cloud.githubusercontent.com/assets/7354362/6776893/e904f944-d176-11e4-83be-82b6ad9593f1.jpg)

**Comment by kartik-v** [comment]
Cannot replicate your error - check the [demo pages](http://demos.krajee.com/widget-details/datepicker#usage) which use the same release.

It can be caching issues on your client - clean up your web server assets folder, clean up your browser cache and restart.

**Comment by trinhkethanh** [comment]
I use same release demo pages of you. 

 <?php
                echo DatePicker::widget([
                    'name' => 'date',
                    'type' => DatePicker::TYPE_COMPONENT_PREPEND,
                    'value' => ArrayHelper::getValue($_REQUEST, 'date', ''),
                    'options' => [
                        'placeholder' => Yii::t('cms', 'select_date')
                    ],
                    'language' => 'en',
                    'pluginOptions' => [
                        'autoclose'=>true,
                        'format' => 'dd-mm-yyyy',
                        'endDate' => date('d-m-Y'),
                    ]
                ]);
?>
However cannot translate language except 'language' => 'en'. When 'language' => 'vi' the error occurred. Thanks so much!

**Comment by kartik-v** [comment]
This is fixed via #29.

Ok this is due to the new noconflict implementation for folks using jquery UI along with this extension. The JUI datepicker uses the same namespace `$.fn.datepicker`.

The new update involved extending bootstrap-datepicker and using its noconflict method to create a new `kvDatepicker` plugin. This was not reflecting in locale / translation files - which is now resolved.

**Comment by trinhkethanh** [comment]
Ok, thanks :)
