### ISSUE TITLE
Default value don't work in datapicker with Model

### ISSUE THREAD

**Issue by cinghie** [kartik-v/yii2-widget-datepicker#31]
Hi kartik-v,

the default value don't work in datapicker with Model:
 
<?= $form->field($model, 'created')->widget(DateTimePicker::classname(), [
        'value' => '23-Feb-1982 10:01',
	'pluginOptions' => [
		'autoclose' => true,
	        'format'    => 'dd-M-yyyy hh:ii',
		'todayHighlight' => true,
	]
]); ?>

If i do the same without Model work fine:

<?php  echo '<label for="items-created" class="control-label">Created</label>';
	echo DateTimePicker::widget([
		'model' => $model,
		'name'  => 'created',
		'value' => '23-Feb-1982 10:01',
		'pluginOptions' => [
		   	'autoclose' => true,
			'format'    => 'dd-M-yyyy hh:ii',
			'todayHighlight' => true
		]
	]);?>

**Comment by cinghie** [comment]
I have found a solution:

<?php echo $form->field($model, 'created')->widget(DateTimePicker::classname(), [
		'options' => [
			'value'    => date("Y-m-d H:i:s"),    
                        'disabled' => 'disabled',
		],
		'pluginOptions' => [
			'autoclose' => true,
			'format'    => 'yyyy-mm-dd hh:ii:ss',
			'todayHighlight' => true,
		]
]); ?>

all the options must be insert in the 'option' paramete and not like the documentation of this Widget

**Comment by kartik-v** [comment]
You are not using it the correct way way as stipulated in Yii MVC structure using model and attribute. 

You may want to read Yii docs (this is true from Yii 1.x) for Yii Input Widgets:

- if you are using the widget without a model - you can set the <b>value</b> property to display initial value. For example:
```php
echo DatePicker::widget([
    'name' => 'date_1',
    'value' =>  '23-Feb-1982 10:01',
]);
```
- if you are using the widget WITH a model (or with ActiveForm) then your initial value must be set ideally on your model attribute.
```php
// Set your model attribute initial value accordingly from your controller action or within the view
$model->date_2 =  '23-Feb-1982 10:01';
// Render widget
echo DatePicker::widget([
    'model' => $model,
    'attribute' => 'date_2'
]);

// Using the same thing as configured above instead with active form

// Set your model attribute initial value accordingly from your controller action or within the view
$model->date_2 =  '23-Feb-1982 10:01';

echo $form->widget($model, 'date_2')->widget(DatePicker::classname(), []);
```

**Comment by Mukhlish** [comment]
test
