### ISSUE TITLE
datepicker is not opening when click

### ISSUE THREAD

**Issue by ajkosh** [kartik-v/yii2-widget-datepicker#32]
plz check below attachment
![screenshot from 2015-04-23 10 44 01](https://cloud.githubusercontent.com/assets/8582472/7290964/d1e57abc-e9a5-11e4-97c3-520af65fb11b.png)

if i m creating new record then it is fine but if i m updating new record it is not working,it is not opening

**Comment by kartik-v** [comment]
You may need to debug your code as this is beyond this extension (and cannot be reproduced).

You may ask for [programming help/tips or such queries related across Yii in this new Q&A forum here](http://webtips.krajee.com/questions).
