### ISSUE TITLE
highlight specific dates

### ISSUE THREAD

**Issue by YairHadari** [kartik-v/yii2-widget-datepicker#33]
Hi,

Can I highlight specific dates so when datepicker will be open the dates will be highlighted?

**Comment by kartik-v** [comment]
You may need to post this query with the plugin author (as I am not aware of this specific requirement as something available with the plugin).

You may also ask for [programming help/tips or such queries related across Yii in this new Q&A forum here](http://webtips.krajee.com/questions).
