### ISSUE TITLE
Bootstrap beforeShowDay functionality in yii2-widget-datepicker

### ISSUE THREAD

**Issue by YairHadari** [kartik-v/yii2-widget-datepicker#34]
Hi,

Is there a way to implement bootstrap beforeShowDay functionality in yii2-widget-datepicker like in

http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on&beforeShowDay=on#sandbox

Thanks,
Yair

**Comment by kartik-v** [comment]
Set it in `pluginOptions` property -- you need to use yii\web\JsExpression to escape javascript expr/callbacks/methods.
