### ISSUE TITLE
Configure addon for prepend, append, and range

### ISSUE THREAD

**Issue by RomeroMsk** [kartik-v/yii2-widget-datepicker#36]
Can't make a configuration for widget to get input group like this:
![image](https://cloud.githubusercontent.com/assets/4639951/7749186/7da84ee6-fff5-11e4-8d09-70842841c822.png)
Tried to use `type = 2` and `addon = 'from'`.

You have an `addon` property, but never use it in code.

**Comment by kartik-v** [comment]
If you are using with ActiveForm... You can use it with `type = 1` (`DatePicker::TYPE_INPUT`) but use  `kartik\widgets\ActiveForm` to render an addon using `kartik\widgets\ActiveField::addon` property. Without Activeform - you can directly render the bootstrap input group markup for `type = 1`.

For other types, it will need an enhancement ... will update.

**Comment by RomeroMsk** [comment]
Oh, it will not work with `yii\bootstrap\ActiveForm`? We have own extended `ActiveForm`...
And making input group markup for `type = 1` is not very nice, but will try. I just thought that it is a bug with `addon` property. Thanks!

**Comment by kartik-v** [comment]
Resolved via 2e45e97.

**Comment by kartik-v** [comment]
[Updated demo for more addons](http://demos.krajee.com/widget-details/datepicker#markup-addons).

**Comment by RomeroMsk** [comment]
Is this new functionality require `kartik\widgets\ActiveForm` to work?

**Comment by kartik-v** [comment]
No it does not require `kartik\widgets\ActiveForm` - but will only work for PREPEND, APPEND, and RANGE types.

**Comment by RomeroMsk** [comment]
Great, thank you!

**Comment by kartik-v** [comment]
I plan to include a better enhancement and push shortly. Refer #47. Heads up... this will break BC - you need to change your code.

This enhancement (like in #47) has also been included in kartik-v/yii2-widget-datetimepicker#401.

**Comment by kartik-v** [comment]
I plan to include a better enhancement and push shortly. Refer #47. Heads up... this will break BC - you need to change your code.

This enhancement (like in #47) has also been included in kartik-v/yii2-widget-datetimepicker#34.
