### ISSUE TITLE
Not sure how to get attributes to POST

### ISSUE THREAD

**Issue by JamesBarnsley** [kartik-v/yii2-widget-datepicker#37]
I am using this code for my DatePicker ...

<?php echo $form->field($profileProject, "dateTo")->widget(DatePicker::classname(), ["attribute" => "dateFrom", "attribute2" => "dateTo", "type" => DatePicker::TYPE_RANGE]); ?>

The problem is when it POSTs it only POSTs the "dateTo" it does not POST the "dateFrom"? I have set attribute1 and attribute2 so I do not get why it does not POST?

**Comment by kartik-v** [comment]
Beyond scope of this widget extension. You need to debug your code and settings. Seems like it could be that you may need to check your model rules and ensure both attributes are marked `safe`.

You may post [such questions and ask for programming tips/queries in this new forum here](http://webtips.krajee.com/questions).
