### ISSUE TITLE
Unable to use event `changeDate` for INLINE type

### ISSUE THREAD

**Issue by Vovan-VE** [kartik-v/yii2-widget-datepicker#43]
When use `INLINE` type, event `changeDate` completely [overwriten by predefined event handler](https://github.com/kartik-v/yii2-widget-datepicker/blob/bf7018663b7ee03cd8d07e623055c9c07f1eb1bf/DatePicker.php#L347):

```php
if ($this->type == self::TYPE_INLINE) {
    $this->pluginEvents = ArrayHelper::merge($this->pluginEvents, ['changeDate' => 'function (e) { ' . $id . '.val(e.format());} ']);
}
```

**Comment by Vovan-VE** [comment]
A workaround is to add event namespace like `changeDate.something`.

**Comment by kartik-v** [comment]
Resolved via latest release. Check [updated demos](http://demos.krajee.com/widget-details/datepicker#markup-inline).
