### ISSUE TITLE
Strange markup for type `INLINE`

### ISSUE THREAD

**Issue by Vovan-VE** [kartik-v/yii2-widget-datepicker#44]
Type `INLINE` produces strange markup: empty "container" followed by its "content". [Code](https://github.com/kartik-v/yii2-widget-datepicker/blame/bf7018663b7ee03cd8d07e623055c9c07f1eb1bf/DatePicker.php#L326):

```php
if ($this->type == self::TYPE_INLINE) {
    ...
    return Html::tag('div', '', $this->_container) . $input;
}
```

May be there was some reasones for this, or may be it's just a typo.

**Comment by kartik-v** [comment]
Resolved via latest release. Check [updated demos](http://demos.krajee.com/widget-details/datepicker#markup-inline).
