### ISSUE TITLE
Event changeDate trigger on page load

### ISSUE THREAD

**Issue by ydakilux** [kartik-v/yii2-widget-datepicker#49]
Hello Kartik,

 When my page load with the following extract

		<?php

        echo $form->field($model, 'initial_use_date')->widget(DateControl::classname(), [
		'type'=>DateControl::FORMAT_DATE,
		'options' => [
			'pluginOptions' => [
			'autoclose' => true
			]
		],
        'pluginEvents' => [
            "changeDate" => "alert('tesssst')",
            ],
		]);
	?>

The event changeDate is triggered when the page is loaded, but not when I change the date with the mouse, strange.... The date change effectively, there also a POST to convert the date
xxx/Yii2_KB/web/datecontrol/parse/convert. everything is OK, except the event who didn't trigger.

 Same issue with a more complex function like

            "changeDate" => "$(function() { needtochangeexpirydate(); })",

       Kinds Regards,
                      Ydaki

**Comment by kartik-v** [comment]
You may need to check plugin documentation... the event you selected is probably triggered after change of the input (not necessarily on change of date in the dropdown picker).
