### ISSUE TITLE
Layout property not defined

### ISSUE THREAD

**Issue by evilito** [kartik-v/yii2-widget-datepicker#51]
The following code:

```
echo DatePicker::widget([
    'type' => DatePicker::TYPE_RANGE,
    'model' => $model,
    'attribute' => 'field1',
    'attribute2' => 'field2',
    'separator' => '<i class="glyphicon glyphicon-resize-horizontal"></i>',
	'layout' => $layout3,
    'pluginOptions' => [
        'autoclose' => true,
        'format' => 'dd-M-yyyy'
    ]
]);
?>
```

throws the following exception: Setting unknown property: kartik\widgets\DatePicker::layout

It should be defined, since according to the documentation, this property is "applicable only when type is one of DatePicker::TYPE_COMPONENT_PREPEND or DatePicker::TYPE_COMPONENT_APPEND or DatePicker::TYPE_RANGE".

Would you please review this issue? Thank you.

**Comment by karataserkan** [comment]
+1

**Comment by kartik-v** [comment]
It seems you have an old outdated release. You need to update to latest release.
