### ISSUE TITLE
setEndDate in changeDate in pluginEvents reset all options set before

### ISSUE THREAD

**Issue by duynguyen0511** [kartik-v/yii2-widget-datepicker#53]
I have a start-date and end-date field and I want to set the "endDate" of start-date to the selected date of end-date.

For example: on page load, start-date and end-date restricts to today. If I select end-date field to Sept 15, then the start-date should not be able to select anything past Sept 15.

here is my php code using pluginEvents (changeDate)

``` php

<?= $form->field($model, 'start_date', ['selectors' => ['input' => '#start-date-id' ], 'options' => ['class' => 'col-md-6'] ])->widget(DatePicker::classname(), [
            'options' => ['placeholder' => 'Enter Date ...', 'id' => 'start-date-id'],
            'type' => DatePicker::TYPE_COMPONENT_APPEND,
            'pluginOptions' => [
                'autoclose'=>true,
                'format' => 'D, mm/dd/yyyy',
                'todayHighlight' => true,
                'todayBtn' => true,
                'endDate' => '0d'
            ]
        ]);
        ?>

        <?= $form->field($model, 'end_date', ['selectors' => ['input' => '#end-date-id' ], 'options' => ['class' => 'col-md-6'] ])->widget(DatePicker::classname(), [
            'options' => ['placeholder' => 'Enter Date ...', 'id' => 'end-date-id'],
            'type' => DatePicker::TYPE_COMPONENT_APPEND,
            'pluginOptions' => [
                'autoclose'=>true,
                'format' => 'D, mm/dd/yyyy',
                'todayHighlight' => true,
                'todayBtn' => true,
                'endDate' => '0d'
            ],
            'pluginEvents' => [
                'changeDate' => 'function(e) {
                    $("#start-date-id").kvDatepicker("setEndDate", e.date);
                }'
            ]
        ]);
        ?>
```

The issue is all the pluginOptions were set previously with start-date gone. The auto-close doesnt work, format is reset to mm/dd/yyyy, todayHightlight is reset, todayBtn is reset. 

I test it with original bootstrap-datepicker and have no issue at all ( http://jsfiddle.net/ox4vjn9r/ ). All my options are reserved.

**Comment by kartik-v** [comment]
Not sure about this - ensure you have the right releases and the plugin version you are testing with matches the plugin version installed with this extension.

**Comment by jcarignan** [comment]
I have the same issue. I ended up overwriting the defaults values I want in JS.

```
//    ¯\_(ツ)_/¯
$.fn.kvDatepicker.defaults.todayHighlight = true;
$.fn.kvDatepicker.defaults.format = 'yyyy-mm-dd';
```

**Comment by phoenixtf** [comment]
So, I found a workaround.
If you would use postfixed selector, e.g. "#[your-selector]-kvdate", you get correct behaviour.
Problem is when we fire ".kvDatepicker(..,)" with no matter which action, it rebuilds datepicker as new, while it has already been build for postfixed selector.

**Comment by mtangoo** [comment]
It's 2020 and @phoenixtf solution saved me hours of pain. Can it be added to the documentation? @kartik-v

**Comment by thion007** [comment]
Hi mtangoo,

maybe you could provide a sample concerning postfixed selector. I'm stuck in the same problem, but it seems I'm lacking some javascript skills...

Thanks in advance.

**Comment by kartik-v** [comment]
@mtangoo / everyone - thanks for your feedback - somehow had skipped this earlier ... will try to add this soon in documentation

**Comment by urielgolab** [comment]
> So, I found a workaround. If you would use postfixed selector, e.g. "#[your-selector]-kvdate", you get correct behaviour. Problem is when we fire ".kvDatepicker(..,)" with no matter which action, it rebuilds datepicker as new, while it has already been build for postfixed selector.

This worked for me: 
`$('#endDate-disp-kvdate').kvDatepicker('setStartDate', e.date);`

**Comment by mtangoo** [comment]
bumped the bug again, lol!

**Comment by kartik-v** [comment]
Hi folks - note that for all types other than `DatePicker::TYPE_INPUT` - the datepicker is initialized not on the TEXT INPUT -- but on the CONTAINER component (which encloses everything e.g. the input and bootstrap styled input group addons, or range, or button). 

The container component has an HTML id attribute= `DatePicker::options['id'] . '-kvdate'` 

So in summary when using the prepend or append addons use the CONTAINER IDENTIFIER as above to reinitialize the Datepicker JQuery plugin - for example

```
$('#endDate-disp-kvdate').kvDatepicker('setStartDate', e.date);
```

This will be updated in the docs as well. Thanks.

**Comment by mtangoo** [comment]
Beautiful. I had always to drop to _INPUT because of this.
Thanks for all extensions you have put forth, for free!
