### ISSUE TITLE
The Datepicker dont open when Click

### ISSUE THREAD

**Issue by ic-armando-1992** [kartik-v/yii2-widget-datepicker#57]
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\LibroCalidad */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="libro-calidad-form">

    <?php $form = ActiveForm::begin(
    	[
    		'options' => [
    			'class' => 'form-modal'
    		]
    	]
    ); ?>

   <?= DatePicker::widget([
	    'name' => 'dp_3',
	    'type' => DatePicker::TYPE_COMPONENT_APPEND,
	    'value' => '23-Feb-1982',
	    'pluginOptions' => [
	        'autoclose'=>true,
	        'format' => 'dd-M-yyyy'
	    ]
	]) ?>

    <?php ActiveForm::end(); ?>

</div>

**Comment by kartik-v** [comment]
You need to check and debug your code. You may cross check with [demo pages and examples](http://demos.krajee.com/widget-details/datepicker#usage).
