### ISSUE TITLE
How to do a codecept acceptance test on a datepicker-field?

### ISSUE THREAD

**Issue by Forin** [kartik-v/yii2-widget-datepicker#7]
I´ve got an active form which includes a datepicker field:
```
    <?= $form->field($model, 'datum')->widget(DateControl::classname(), [
                'type'=>DateControl::FORMAT_DATE,
                'options' => [
                    'pluginOptions' => [
                         'autoclose' => true,
                     ]
                ]
    ]);   ?>
```

That works fine, I can enter or choose "31.12.2014" (German/DE dateformat) and the date will be stored to the "datum" field.

I tried to do a codecept acceptance test on that form:

```
$I->fillField('input[name="datum-address-datum"]', '31.12.2014');
$I->click('Save');
$I->see('31.12.2014');
```

The fillField-command works (field is found and I think 31.12.2014 gets inserted) but the date is not saved, see('31.12.2014') fails, the date is not saved to database and not shown in the detailview.

I also tried
```
$I->fillField('input[id=address-datum-disp]', '31.12.2014');
```
and
```
$I->fillField('input[name="Address[datum]"]', '31.12.2014');
```
But none of them works.

So the question is how can a  codecept acceptance test be done on a datepicker-field?

**Comment by kartik-v** [comment]
Closing this as not heard back. In case you have an issue - it can be reopened.

**Comment by ikerib** [comment]
> $I->pressKey('input[id=address-datum-disp]', WebDriverKeys::TAB);

this works for me. thx!
