### ISSUE TITLE
Use 1.3.6+ with yii\grid\GridView

### ISSUE THREAD

**Issue by Razzwan** [kartik-v/yii2-widget-datepicker#70]
When I try use 1.3.6+ version with yii\grid\GridView, I can`t open page with widget: returns to the previous page. 1.3.5 version and previous have not this problem.

**Comment by kartik-v** [comment]
You may [want to check this](https://github.com/kartik-v/yii2-widget-datepicker/issues/20#issuecomment-74255095)
