### ISSUE TITLE
Strange behavior with format

### ISSUE THREAD

**Issue by astappiev** [kartik-v/yii2-widget-datepicker#73]
Hey! I have a problem and hope that somebody can help me to solve it.
After that I call setDaysOfWeekDisabled a 'format' of datepicker was returned back to default 'mm/dd/yyyy' instead of format that I setup 'dd/mm/yyyy'.

Steps to reproduce:
1. Create a widget e.g.

```
<?= \kartik\date\DatePicker::widget([
    'id' => 'example'
    'type' => \kartik\date\DatePicker::TYPE_COMPONENT_APPEND,
    'pluginOptions' => [
        'todayHighlight' => true,
        'format' => 'dd/mm/yyyy',
        'weekStart' => 0,
        'startDate' => 'd',
        'endDate' => '+2w',
    ],
]); ?>
```
1. Call any method from js, e.g.
   `$('#example').kvDatepicker('setDaysOfWeekDisabled', [1,5,6]);`
2. Try to select new value, the dates will be in wrong format

Did somebody solve the problem?

Thanks!

**Comment by bhattaxay** [comment]
You have to change the format of date From-> dd/mm/yyyy To->dd-mm-yyyy while submit the form. It store the date in this format To->dd-mm-yyyy of the database
