### ISSUE TITLE
date clear/remove button not working

### ISSUE THREAD

**Issue by R13e** [kartik-v/yii2-widget-datepicker#75]
If you have setup a Datepicker widget, the remove button has no effect. The **hidden** input field still holds the last selected value. In contrast to, a fully delete with the keyboard has the expected behavior.
I think it is the [https://github.com/kartik-v/yii2-widget-datepicker/blob/master/assets/js/datepicker-kv.js#L22](https://github.com/kartik-v/yii2-widget-datepicker/blob/master/assets/js/datepicker-kv.js#L22) but I'm not able to be digging any further.

You can check the behavior for the type **date** on the [demo](http://demos.krajee.com/datecontrol-demo) page. The **Input saved as: ** has still the value.

**Comment by R13e** [comment]
Many thanks. Great work!

**Comment by drew1two** [comment]
I'm having the same problem when using via GridView::FILTER_DATE
I'm using ver 1.4.7 of the  yii2-widget-datepicker
yii2 ver 2.0.40 
php 7.3.15
"kartik-v/yii2-datecontrol": "@dev"

Yet it seems to work fine when using Editable::INPUT_DATE
Haven't put my finger on it yet... still looking.
