### ISSUE TITLE
Class 'kartik\field\FieldRangeAsset' not found

### ISSUE THREAD

**Issue by ApexWire** [kartik-v/yii2-widget-datepicker#76]
You have the same error as it occured in https://github.com/kartik-v/yii2-widgets/issues/145

Commit: https://github.com/kartik-v/yii2-widget-datepicker/commit/73d0a3ee922e383f332dcde00e2f411b7ebe54f7#diff-ef110bd52ec2cb482966b53232ef13f5

**Comment by kartik-v** [comment]
No you should get a meaningful exception message to install the yii2-field-range extension. You may need to ensure you have the right latest version of the extension. This cannot be reproduced.
