### ISSUE TITLE
Datepicker does not work with search input

### ISSUE THREAD

**Issue by PubliusEnigma** [kartik-v/yii2-widget-datepicker#80]
Hello.

I'm trying to implement datepicker in search input in GridView in index.php file.

The example is here (but with 2amigos DatePicker widget) - I tried to use Kartik widget instead, but it does not work.

My code in index.php:

```
            [
                'attribute' => 'start_date',
                'value' => 'start_date',
                'format' => 'raw',
                'label' => "Date open",
                'filter' => DatePicker::widget([
                    'model' => $searchModel, 
                    'name' => 'start_date', 
                    'value' => 'start_date',
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd',
                        'autoclose' => true,
                    ]
                ]) 

            ],
```

I have already found workaround to make this plugin work, by putting this code in place of 'name':
`'name' => 'BrokerAccountSearch[start_date]', `

It works, but after I choose a date from the widget (2016-02-01), it shows right data...

![1](https://cloud.githubusercontent.com/assets/375887/13380449/0923e458-de44-11e5-9853-143809179c7f.PNG)

... but the choosen date disappears from input field:
![2](https://cloud.githubusercontent.com/assets/375887/13380450/0925d4ca-de44-11e5-968a-b9a1d5c7ffef.PNG)

Isn't a bug? Or my configuracion is bad?

**Comment by PubliusEnigma** [comment]
Ok I solved it, but I don't know if it is a optimal solution.
I put this code in 'value' field:

`'value' => ArrayHelper::getValue($_GET, "BrokerAccountSearch.start_date"),`

**Comment by kartik-v** [comment]
You have a simpler way to configure this. Check [yii2-grid documentation](http://demos.krajee.com/grid) and [yii2-grid demos](http://demos.krajee.com/grid/demo).

You can directly set a special `filterType` property for the data column to `GridView::INPUT_DATE` and use `filterWidgetOptions` to configure your date picker widget options.
