### ISSUE TITLE
Datagrid sorting problem in Chrome from v 1.3.4

### ISSUE THREAD

**Issue by peresz** [kartik-v/yii2-widget-datepicker#83]
After upgrade from 1.3.3 to 1.3.4 problems with sorting datagrid (pjax) appeared in Chrome browser. Page reloads twice. Finally I get data not sorted.

**Comment by kartik-v** [comment]
I am not sure why you are using an older release. The latest release is v1.3.8. Anyway I cannot reproduce this error for yii2-grid. You may want to check your code and update.
