### ISSUE TITLE
Datepicker forces infinite reload of GridView

### ISSUE THREAD

**Issue by ak1987** [kartik-v/yii2-widget-datepicker#87]
Hello, I have a problem after update, and didn't find a solution.
The problem is in the code:

'class' => 'kartik\grid\EditableColumn',
            'attribute' => 'date_wish_set',
            'filterType' => GridView::FILTER_DATE,
            'filterWidgetOptions' => [
                'type' => 1,
                'value'=> NULL,
                'pluginOptions' => [
                    'autoclose' => true,
                    'locale' => [
                        'format' => 'yyyy-mm-dd',
                    ]
                ]
            ],

When i DO NOT use filterWidgetOptions evertthing works fine, and page don't reload. But when I add format or anything other property to pluginOptions array error appears.

**Comment by kartik-v** [comment]
Use type property other than 1.. To prepend or append component.

 This is a source plugin behavior which triggers a change on the input on load only for type = 1.... resulting in the infinite loop as it triggers the grid to query and reload.
