### ISSUE TITLE
clearBtn doesn't trigger page reload in v.1.3.9

### ISSUE THREAD

**Issue by shum16** [kartik-v/yii2-widget-datepicker#88]
I had to rollback to version 1.3.3 to get it to work as it should. My plugin settings:
`'filterType' => GridView::FILTER_DATE,
			'filterWidgetOptions' => [
				'removeButton' => false,
				'pluginOptions' => [
					'format' => 'yyyy-mm-dd',
					'minViewMode' => 1,
					'clearBtn' => true
				],							
			],`

**Comment by kartik-v** [comment]
Not sure of your problem as cannot reproduce what you are saying -- the latest release of the extension is v1.4.0 ... you may check and update.
