### ISSUE TITLE
Include css source map or remove link

### ISSUE THREAD

**Issue by nicomollet** [kartik-v/yii2-widget-datepicker#89]
Hello

I am getting errors like:
yii\base\InvalidRouteException' with message 'Unable to resolve the request "assets/c7fa88e4/css/bootstrap-datepicker3.css.map"

It seems the link to the source map `/*# sourceMappingURL=bootstrap-datepicker3.css.map */` is included in the css file bootstrap-datepicker3(.min).css.

Looking at your other projects, I think the link should be removed.
https://github.com/kartik-v/yii2-widget-datepicker/commit/af32eeee557fa12e1b362e24fd8d0bc14713e361#commitcomment-17255491

**Comment by kartik-v** [comment]
You may upgrade to latest release (v1.4.0) of the extension.

**Comment by hdewaart** [comment]
Still seems to load bootstrap-datepicker3.css.map
If I remove this line, the error is gone

**Comment by nicomollet** [comment]
sourceMappingURL is still here. @kartik-v did you remove the line in the latest releases 1.4.0 and 1.4.1? I can't confirm this has been done.
