### ISSUE TITLE
Is convertFormat changed?

### ISSUE THREAD

**Issue by a-komarev** [kartik-v/yii2-widget-datepicker#9]
I've noticed that datetime picker has stopped to work as expected. I haven't changed it since middle of november.
I had this code in view:
```
$form->field($model, 'birthDate')->widget(
    DatePicker::classname(),
    [
        'convertFormat' => true,
        'pluginOptions' => [
            'language' => 'ru',
            'endDate' => '31-12-1999',
            'format' => 'd-m-Y',
            'autoclose' => true,
            'startView' => 'decade',
        ]
    ]
); ?>
```
If i'm picking 04 January 2015 - in input I'm recieving: `1-ii-o` and it has returned `04-02-2015` before.

Now I've changed my view to this:
```
$form->field($model, 'birthDate')->widget(
    DatePicker::classname(),
    [
        'pluginOptions' => [
            'endDate' => '31-12-1999',
            'format' => 'dd-mm-yyyy',
            'autoclose' => true,
            'startView' => 'decade',
        ]
    ]
); ?>
```
And now it's working good.
So I've just removed convertFormat and wrote format in pluginOptions. It's seems to work now, but i'm not sure it's compatible for all situations.

**Comment by kartik-v** [comment]
If you are using convertFormat to true .. the format will be first parsed using Yii's i18n FormatConverter... and then converted to plugin's format

By default Yii expects ICU date format - and you need to prepend the string `php:` if you are using PHP date format.

So in your case to summarize you must use the format `php:d-m-Y1 and it should work i.e.

```php
$form->field($model, 'birthDate')->widget(
    DatePicker::classname(),
    [
        'convertFormat' => true,
        'pluginOptions' => [
            'language' => 'ru',
            'endDate' => '31-12-1999',
            'format' => 'php:d-m-Y',
            'autoclose' => true,
            'startView' => 'decade',
        ]
    ]
);
```

**Comment by a-komarev** [comment]
Thanks. Redone it using ICU format:
```
$form->field($model, 'birthDate')->widget(
    DatePicker::classname(),
    [
        'convertFormat' => true,
        'pluginOptions' => [
            'endDate' => '31-12-1999',
            'format' => 'dd-MM-yyyy',
            'autoclose' => true,
            'startView' => 'decade',
        ]
    ]
);
```

P.S. Language options isn't working anymore because it's only using Yii::$app->language value.

**Comment by kartik-v** [comment]
Language option does work. Hope you have the updated plugin release. What's the error you are facing?

**Comment by a-komarev** [comment]
I've made a new issue for it, thanks!
https://github.com/kartik-v/yii2-widget-datepicker/issues/10
