### ISSUE TITLE
Здесь на руском можно писать? вопрос по DateTimePicker

### ISSUE THREAD

**Issue by lycifer3** [kartik-v/yii2-widget-datepicker#90]
У меня проблема с datetimepicker на одной странице вызываю модальное окно в которо подключен datetimepicker на другой странице вызывая то же модальное окно выдает ошибку 
TypeError: jQuery(...).datetimepicker is not a function
вот мой datetimepicker

на обеих страницах получаю его обращаясь к одному и тому же методу ответ делаю через renderAjax

<?= DateTimePicker::widget([
                        'name' => 'comment',
                        'value' => 'Выберите время приема',
                        'type' => DateTimePicker::TYPE_COMPONENT_PREPEND,
                        'language' => Yii::$app->language,
                        'layout' => '{picker}{input}{remove}',
                        'options' => ['class' => 'form-input'],
                        'pluginOptions' => [
                            'format' => 'dd-MM-yyyy HH:ii P',
                            'startDate' => date('d-m-Y h:i:s'),
                            'autoclose' => true,
                            'class' => 'form-input'
                        ],
                        'pluginEvents' => [
                            "hide" => "function(e) {  $('.input-block-date').removeClass('danger') }",
                        ]
                    ]); ?>

**Comment by Denis4yk** [comment]
@lycifer3 
Можно, но, боюсь, не поможет)
