### ISSUE TITLE
If select today date it becomes the month before

### ISSUE THREAD

**Issue by aller** [kartik-v/yii2-widget-datepicker#94]
Today is June 27, July is active month - we will get May 27.

How to recreate:
1) http://demos.krajee.com/widget-details/datepicker#advanced-usage
2) Birth Date (Highlight today, show today button, change date format)
3) open datepicker
4) go to July month
5) June 27 (today) is highlighted
6) click on today date

**Comment by kartik-v** [comment]
Cannot reproduce your use case (seems to work ok) ... it navigates to the today date month correctly..

**Comment by aller** [comment]
here is a video http://screencast.com/t/tTtOTlaNoQTt

**Comment by kartik-v** [comment]
This is a plugin specific bug.

Anyway refer #95 ... the extension is now updated to release v1.4.0 and it uses the latest dev code v1.7.x of the plugin where this works fine.

**Comment by aller** [comment]
yep, fixed
thx a lot
