### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dates' of undefined.

### ISSUE THREAD

**Issue by jeroenk22** [kartik-v/yii2-widget-datepicker#96]
Hello Kartik,

Since your last update of Datepicker (v1.4.0) I receive the following JS error:

`Uncaught TypeError: Cannot read property 'dates' of undefined.`

I'm using Dutch language.

My code:
```

        <?= DatePicker::widget([
        'name' => 'nieuweDatum',
        'type' => DatePicker::TYPE_BUTTON,
        'language' => 'nl',
        'pluginOptions' => [
            'todayHighlight' => true,
            'autoclose' => true,
            'format' => 'yyyy-mm-dd',
            'calendarWeeks' => true,
            'todayBtn' => true,
        ],                   
            'pluginEvents' => [
                "changeDate" => "function(e) { $.get(datum, {datum: $(this).find('input').val()} ); $.pjax.reload({container: '#planner_grid', timeout: 10000}); }",  
            ]
        ]);?>

```

**Comment by kartik-v** [comment]
The problem is in your plugin events code... you need to check the [plugin documentation](https://bootstrap-datepicker.readthedocs.io/en/stable/index.html) for the updated plugin event params.

**Comment by jeroenk22** [comment]
Can you please give me a hint? The changeDate event still works like it did before. If I comment out the whole `pluginEvents` the JS error still persists.. The only difference since the last update is that I can't use Dutch (or whatever language) anymore.

**Comment by kartik-v** [comment]
OK I think I know the issue... Will update

**Comment by kartik-v** [comment]
I think this should resolve the issue - check and let know and then will tag this release.

**Comment by jeroenk22** [comment]
Thank you! The problem is has been solved.

**Comment by intricareruchika** [comment]
i have same issue and i haven't write code of plugin events
my code is..

  <?= $form->field($model, 'date_of_join')->widget(DatePicker::classname(), [
    'options' => ['placeholder' => 'Enter birth date ...'],
	'name' => 'date_of_join',
    'pluginOptions' => [
        'autoclose'=>true
    ],


issue is=Uncaught TypeError: Cannot set property 'dates' of undefined
