### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by borison89** [kartik-v/yii2-widget-datepicker#99]
I have error on log in browser
(kartik-v/yii2-widget-datepicker (v1.4.0))

bootstrap-datepicker.ru.min.js:1 Uncaught TypeError: Cannot read property 'dates' of undefined

dates undefined
!function(a){a.fn.datepicker.dates.ru.......

now windget use English language (i think for default)

**Comment by kartik-v** [comment]
Duplicate to #96. Upgrade to release v1.4.1.
